# Generated by Django 2.2 on 2023-07-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_record', '0004_auto_20230726_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='doctor_id',
            new_name='user_id',
        ),
    ]
