# Generated by Django 2.2 on 2023-07-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_record', '0006_remove_department_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecords',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
